const mediaTypes = {
    'application/json': ['.json'],
    'application/xml': ['.xml'],
    'application/javascript': ['.js'],
    'application/octet-stream': ['.bin', '.exe', '.dll', '.class'],
    'application/pdf': ['.pdf'],
    'application/zip': ['.zip'],
    'application/x-www-form-urlencoded': ['.urlencoded'],
    'application/x-tar': ['.tar'],
    'application/x-gzip': ['.gz'],
    'application/vnd.ms-excel': ['.xls', '.xlsx'],
    'application/vnd.ms-powerpoint': ['.ppt', '.pptx'],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': [
      '.docx',
    ],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': [
      '.xlsx',
    ],
    'text/html': ['.html', '.htm'],
    'text/css': ['.css'],
    'text/plain': ['.txt'],
    'text/xml': ['.xml'],
    'text/markdown': ['.md'],
    'text/csv': ['.csv'],
    'image/jpeg': ['.jpg', '.jpeg'],
    'image/png': ['.png'],
    'image/gif': ['.gif'],
    'image/svg+xml': ['.svg'],
    'image/webp': ['.webp'],
    'image/bmp': ['.bmp'],
    'image/tiff': ['.tif', '.tiff'],
    'image/vnd.microsoft.icon': ['.ico'],
    'audio/mpeg': ['.mp3'],
    'audio/wav': ['.wav'],
    'audio/ogg': ['.ogg', '.oga'],
    'audio/mp4': ['.m4a'],
    'video/mp4': ['.mp4'],
    'video/x-msvideo': ['.avi'],
    'video/x-flv': ['.flv'],
    'video/quicktime': ['.mov'],
    'video/x-matroska': ['.mkv'],
    'video/webm': ['.webm'],
    'application/x-shockwave-flash': ['.swf'],
    'application/vnd.apple.installer+xml': ['.pkg'],
    'application/vnd.ms-cab-compressed': ['.cab'],
    'application/x-font-ttf': ['.ttf'],
    'application/x-font-opentype': ['.otf'],
    'application/x-font-woff': ['.woff'],
    'application/vnd.ms-fontobject': ['.eot'],
    'application/vnd.google-apps.document': ['.gdoc'],
    'application/vnd.google-apps.presentation': ['.gslide'],
    'application/vnd.google-apps.spreadsheet': ['.gsheet'],
  };
  
  export function getExtensions(content_type:string):string[] {
    return mediaTypes[content_type] || [];
  }
  